export const Reglas={
    0:{
        tiempoLinea:1300,
        tiempoBonifica:80,
        movimiento:false,
    },
    1:{
        tiempoLinea:1000,
        tiempoBonifica:60,
        movimiento:false,
    },
    2:{
        tiempoLinea:800,
        tiempoBonifica:45,
        movimiento:false,
    },
    3:{
        tiempoLinea:1000,
        timpoBonifica:45,
        movimiento:true,
    }
}